# Generated by Django 3.0.7 on 2020-06-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0004_category_slug'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_categories',
            field=models.ManyToManyField(to='news.Category'),
        ),
    ]
