# Generated by Django 3.0.3 on 2020-08-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('sort', models.SmallAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sort', models.SmallAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(null=True)),
                ('full_image', models.URLField(null=True)),
                ('detail_url', models.URLField()),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                               to='news.Category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                             to='news.Source')),
                ('tags', models.ManyToManyField(related_name='posts', to='news.PostTag')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=15)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                           to='news.Post')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
