# Generated by Django 3.0.7 on 2020-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=15, unique=True),
        ),
    ]
