# Generated by Django 3.0.7 on 2020-06-29 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-timestamp',)},
        ),
    ]
