# Generated by Django 3.0.7 on 2020-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0005_auto_20200629_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-priority',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('-priority',)},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='priority',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
