# Generated by Django 3.0.3 on 2020-07-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0006_auto_20200630_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
