# Generated by Django 3.0.3 on 2020-07-19 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0007_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('sort',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='priority',
            new_name='sort',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='priority',
            new_name='sort',
        ),
    ]
